---
- name: Set up Apache Web Server on Demo Servers
  hosts: demo_servers
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Debug variable values
      ansible.builtin.debug:
        msg:
          - "http_port: {{ http_port }}"
          - "server_admin_email: {{ server_admin_email }}"
          - "document_root: {{ document_root }}"

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Deploy Apache configuration template
      ansible.builtin.template:
        src: templates/apache2.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      notify:
        - restart apache

  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"

