---
- name: Install necessary software packages
  hosts: demo_servers
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install PHP
      ansible.builtin.apt:
        name: php
        state: present
      when: ansible_os_family == "Debian"

    - name: Install PHP MySQL module
      ansible.builtin.apt:
        name: php-mysql
        state: present
      when: ansible_os_family == "Debian"

    # Add more tasks to install additional packages as needed

